### ISSUE TITLE
@LevLeoLevLeo

### ISSUE THREAD

**Issue by yobafromstarvvars** [yobafromstarvvars/cuddly-octo-broccoli#2]
**@LevLeoLevLeo** 
_Ответить на следующие вопросы по теме "Актуальность":_ 
- [x]  1. Почему данный сервис в наши дни пользуется спросом? 
- [x]  2. Почему услуги сопровождающего будут актуальны на средней срочной перспективе? 
- [x]  3. Насколько услуги придётся дополнять/изменять, чтобы сохранить или повысить актуальность?

_Ответить на следующие вопросы об реализуемости:_ 
- [x]  1. Сколько ресурсов необходимо затратить для реализации сервиса?

**Comment by LevLeoLevLeo** [comment]
All done,

**Comment by yobafromstarvvars** [comment]
nice!
